# Generated by Django 5.2.9 on 2025-12-22 12:16

import django.db.models.deletion
import modelcluster.fields
import modelsearch.index
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('introduction', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ConflictArc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabula_uuid', models.CharField(help_text='UUID from Fabula graph (arc_uuid)', max_length=100, unique=True)),
                ('title', models.CharField(help_text='Short title for the arc', max_length=255)),
                ('description', models.TextField(help_text='Description of the conflict and its stakes')),
                ('arc_type', models.CharField(choices=[('INTERNAL', 'Internal'), ('INTERPERSONAL', 'Interpersonal'), ('SOCIETAL', 'Societal'), ('ENVIRONMENTAL', 'Environmental'), ('TECHNOLOGICAL', 'Technological')], default='INTERPERSONAL', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Conflict Arc',
                'verbose_name_plural': 'Conflict Arcs',
            },
            bases=(modelsearch.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='ConnectionIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('introduction', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='EpisodePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('fabula_uuid', models.CharField(blank=True, help_text='UUID from Fabula graph (episode_uuid)', max_length=100)),
                ('episode_number', models.PositiveIntegerField()),
                ('logline', models.TextField(blank=True, help_text='One-sentence summary of the episode')),
                ('high_level_summary', wagtail.fields.RichTextField(blank=True, help_text='Detailed episode summary')),
                ('dominant_tone', models.CharField(blank=True, help_text='The prevailing emotional/atmospheric tone', max_length=100)),
            ],
            options={
                'ordering': ['episode_number'],
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='EventIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('introduction', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='OrganizationIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('introduction', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='OrganizationPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('fabula_uuid', models.CharField(blank=True, help_text='UUID from Fabula graph (org_uuid)', max_length=100)),
                ('canonical_name', models.CharField(max_length=255)),
                ('description', wagtail.fields.RichTextField()),
                ('sphere_of_influence', models.CharField(blank=True, help_text='Primary domain of operation', max_length=255)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='SeasonPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('fabula_uuid', models.CharField(blank=True, help_text='UUID from Fabula graph (season_uuid)', max_length=100)),
                ('season_number', models.PositiveIntegerField()),
                ('description', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'ordering': ['season_number'],
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='SeriesIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('fabula_uuid', models.CharField(blank=True, help_text='UUID from Fabula graph (series_uuid)', max_length=100)),
                ('description', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabula_uuid', models.CharField(help_text='UUID from Fabula graph (theme_uuid)', max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(help_text='Thematic description explaining how this theme manifests')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Themes',
            },
            bases=(modelsearch.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='ThemeIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('introduction', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabula_uuid', models.CharField(help_text='UUID from Fabula graph (location_uuid)', max_length=100, unique=True)),
                ('canonical_name', models.CharField(max_length=255)),
                ('description', models.TextField(help_text='Physical and atmospheric description of the location')),
                ('location_type', models.CharField(blank=True, help_text="Categorical type (e.g., 'West Wing Executive Office')", max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_location', models.ForeignKey(blank=True, help_text='Parent location for hierarchical relationships', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_locations', to='narrative.location')),
            ],
            options={
                'verbose_name_plural': 'Locations',
            },
            bases=(modelsearch.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='EventPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('fabula_uuid', models.CharField(blank=True, help_text='UUID from Fabula graph (event_uuid)', max_length=100)),
                ('scene_sequence', models.PositiveIntegerField(default=0, help_text='Scene number within episode')),
                ('sequence_in_scene', models.PositiveIntegerField(default=0, help_text='Event sequence within scene')),
                ('description', wagtail.fields.RichTextField(help_text='Full description of what happens in this event')),
                ('key_dialogue', models.JSONField(blank=True, default=list, help_text='Notable dialogue from this event')),
                ('is_flashback', models.BooleanField(default=False, help_text='Whether this event is a flashback')),
                ('arcs', modelcluster.fields.ParentalManyToManyField(blank=True, related_name='events', to='narrative.conflictarc')),
                ('episode', models.ForeignKey(help_text='The episode this event belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='events', to='narrative.episodepage')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='narrative.location')),
                ('themes', modelcluster.fields.ParentalManyToManyField(blank=True, related_name='events', to='narrative.theme')),
            ],
            options={
                'ordering': ['episode__episode_number', 'scene_sequence', 'sequence_in_scene'],
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='CharacterPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('fabula_uuid', models.CharField(blank=True, help_text='UUID from Fabula graph (agent_uuid)', max_length=100)),
                ('canonical_name', models.CharField(help_text="Primary name (e.g., 'Joshua Lyman')", max_length=255)),
                ('title_role', models.CharField(blank=True, help_text="Official title or role (e.g., 'Deputy Chief of Staff')", max_length=255)),
                ('description', wagtail.fields.RichTextField(help_text='Foundational character description')),
                ('traits', models.JSONField(default=list, help_text='List of foundational character traits')),
                ('nicknames', models.JSONField(default=list, help_text='Alternative names and nicknames')),
                ('character_type', models.CharField(choices=[('main', 'Main Character'), ('recurring', 'Recurring Character'), ('guest', 'Guest Character'), ('mentioned', 'Mentioned Only')], default='recurring', max_length=50)),
                ('sphere_of_influence', models.CharField(blank=True, help_text='Primary domain of authority or expertise', max_length=255)),
                ('appearance_count', models.PositiveIntegerField(default=0, help_text='Number of event appearances')),
                ('affiliated_organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affiliated_characters', to='narrative.organizationpage')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='CharacterEpisodeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabula_uuid', models.CharField(blank=True, help_text='UUID from Fabula graph (profile_uuid)', max_length=100)),
                ('description_in_episode', models.TextField(blank=True, help_text="Character's state/role in this specific episode")),
                ('traits_in_episode', models.JSONField(default=list, help_text='Traits observed in this episode')),
                ('contradictions', models.JSONField(blank=True, default=list, help_text='Contradictions or tensions observed')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episode_profiles', to='narrative.characterpage')),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_profiles', to='narrative.episodepage')),
            ],
            options={
                'verbose_name': 'Character Episode Profile',
                'verbose_name_plural': 'Character Episode Profiles',
                'unique_together': {('character', 'episode')},
            },
        ),
        migrations.CreateModel(
            name='EventParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('emotional_state', models.TextField(blank=True, help_text="Character's emotional state during this event")),
                ('goals', models.JSONField(default=list, help_text="Character's goals in this moment")),
                ('what_happened', models.TextField(blank=True, help_text='Description of what the character did')),
                ('observed_status', models.TextField(blank=True, help_text='Observable status or role in the event')),
                ('beliefs', models.JSONField(blank=True, default=list, help_text="Character's beliefs active in this moment")),
                ('observed_traits', models.JSONField(blank=True, default=list, help_text='Character traits observable in this event')),
                ('importance', models.CharField(blank=True, help_text='primary, secondary, background, etc.', max_length=50)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_participations', to='narrative.characterpage')),
                ('event', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='narrative.eventpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'unique_together': {('event', 'character')},
            },
        ),
        migrations.CreateModel(
            name='NarrativeConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabula_uuid', models.CharField(blank=True, help_text='UUID from Fabula graph (connection_uuid)', max_length=100)),
                ('connection_type', models.CharField(choices=[('CAUSAL', 'Causal'), ('FORESHADOWING', 'Foreshadowing'), ('THEMATIC_PARALLEL', 'Thematic Parallel'), ('CHARACTER_CONTINUITY', 'Character Continuity'), ('ESCALATION', 'Escalation'), ('CALLBACK', 'Callback'), ('EMOTIONAL_ECHO', 'Emotional Echo'), ('SYMBOLIC_PARALLEL', 'Symbolic Parallel'), ('TEMPORAL', 'Temporal')], max_length=50)),
                ('strength', models.CharField(choices=[('strong', 'Strong'), ('medium', 'Medium'), ('weak', 'Weak')], default='medium', max_length=20)),
                ('description', models.TextField(help_text="The narrative assertion explaining WHY these events connect. This is the 'content' of the connection - the edge carries meaning.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_connections', to='narrative.eventpage')),
                ('to_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_connections', to='narrative.eventpage')),
            ],
            options={
                'ordering': ['connection_type', '-strength'],
                'unique_together': {('from_event', 'to_event', 'connection_type')},
            },
        ),
    ]
