# Generated by Django 5.2.9 on 2025-12-22 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narrative', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterpage',
            name='nicknames',
            field=models.JSONField(blank=True, default=list, help_text='Alternative names and nicknames'),
        ),
        migrations.AlterField(
            model_name='characterpage',
            name='traits',
            field=models.JSONField(blank=True, default=list, help_text='List of foundational character traits'),
        ),
    ]
