# Generated by Django 5.2.9 on 2025-12-26 13:47

from pathlib import Path
from django.db import migrations
import yaml


def cleanup_deprecated_entities(apps, schema_editor):
    """
    Remove deprecated entities that are not in the current YAML export.

    This runs once during migration to clean up entities that were imported
    before the export was filtered to only include canonical entities.
    """
    CharacterPage = apps.get_model('narrative', 'CharacterPage')
    OrganizationPage = apps.get_model('narrative', 'OrganizationPage')
    Location = apps.get_model('narrative', 'Location')

    # Find the fabula_export directory relative to the project
    base_dir = Path(__file__).resolve().parent.parent.parent
    export_dir = base_dir / 'fabula_export'

    if not export_dir.exists():
        print(f"  Export directory not found: {export_dir}")
        return

    total_deleted = 0

    # Cleanup Characters
    characters_file = export_dir / 'characters.yaml'
    if characters_file.exists():
        with open(characters_file, 'r') as f:
            data = yaml.safe_load(f) or []
        canonical_uuids = {c.get('fabula_uuid') for c in data if c.get('fabula_uuid')}

        deprecated = CharacterPage.objects.exclude(fabula_uuid='').exclude(fabula_uuid__in=canonical_uuids)
        count = deprecated.count()
        if count > 0:
            print(f"  Deleting {count} deprecated CharacterPage objects...")
            deprecated.delete()
            total_deleted += count

    # Cleanup Organizations
    orgs_file = export_dir / 'organizations.yaml'
    if orgs_file.exists():
        with open(orgs_file, 'r') as f:
            data = yaml.safe_load(f) or []
        canonical_uuids = {o.get('fabula_uuid') for o in data if o.get('fabula_uuid')}

        deprecated = OrganizationPage.objects.exclude(fabula_uuid='').exclude(fabula_uuid__in=canonical_uuids)
        count = deprecated.count()
        if count > 0:
            print(f"  Deleting {count} deprecated OrganizationPage objects...")
            deprecated.delete()
            total_deleted += count

    # Cleanup Locations
    locations_file = export_dir / 'locations.yaml'
    if locations_file.exists():
        with open(locations_file, 'r') as f:
            data = yaml.safe_load(f) or []
        canonical_uuids = {l.get('fabula_uuid') for l in data if l.get('fabula_uuid')}

        deprecated = Location.objects.exclude(fabula_uuid='').exclude(fabula_uuid__in=canonical_uuids)
        count = deprecated.count()
        if count > 0:
            print(f"  Deleting {count} deprecated Location objects...")
            deprecated.delete()
            total_deleted += count

    print(f"  Cleanup complete: deleted {total_deleted} deprecated entities")


def noop(apps, schema_editor):
    """Reverse migration does nothing - can't restore deleted data."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('narrative', '0002_alter_characterpage_nicknames_and_more'),
    ]

    operations = [
        migrations.RunPython(cleanup_deprecated_entities, noop),
    ]
