# Generated by Django 5.2.9 on 2025-12-29 17:48

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narrative', '0003_cleanup_deprecated_entities'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('introduction', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ObjectPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('fabula_uuid', models.CharField(blank=True, help_text='UUID from Fabula graph (object_uuid)', max_length=100)),
                ('canonical_name', models.CharField(max_length=255)),
                ('description', wagtail.fields.RichTextField(help_text='Description of the object and its appearance')),
                ('purpose', models.TextField(blank=True, help_text='The foundational purpose of this object in the narrative')),
                ('significance', models.TextField(blank=True, help_text='The narrative significance of this object')),
                ('potential_owner', models.ForeignKey(blank=True, help_text='Character who typically owns or possesses this object', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_objects', to='narrative.characterpage')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='LocationInvolvement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('description_of_involvement', models.TextField(blank=True, help_text='How this location features in this event')),
                ('observed_atmosphere', models.TextField(blank=True, help_text='The mood and atmosphere of the location during this event')),
                ('functional_role', models.TextField(blank=True, help_text='The functional role the location plays (meeting place, sanctuary, etc.)')),
                ('symbolic_significance', models.TextField(blank=True, help_text='Any symbolic meaning the location carries in this context')),
                ('access_restrictions', models.TextField(blank=True, help_text='Who can access this location during the event')),
                ('key_environmental_details', models.JSONField(default=list, help_text='Notable environmental details (lighting, sounds, etc.)')),
                ('event', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_involvements', to='narrative.eventpage')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_involvements', to='narrative.location')),
            ],
            options={
                'ordering': ['sort_order'],
                'unique_together': {('event', 'location')},
            },
        ),
        migrations.CreateModel(
            name='ObjectInvolvement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('description_of_involvement', models.TextField(blank=True, help_text='How this object is used or relevant in this event')),
                ('status_before_event', models.TextField(blank=True, help_text='State of the object before this event')),
                ('status_after_event', models.TextField(blank=True, help_text='State of the object after this event')),
                ('event', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_involvements', to='narrative.eventpage')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_involvements', to='narrative.objectpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'unique_together': {('event', 'object')},
            },
        ),
        migrations.CreateModel(
            name='OrganizationInvolvement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('description_of_involvement', models.TextField(blank=True, help_text='How this organization is involved in this event')),
                ('active_representation', models.TextField(blank=True, help_text='Who or what represents the organization in this event')),
                ('power_dynamics', models.TextField(blank=True, help_text='The power dynamics the organization displays')),
                ('organizational_goals', models.JSONField(default=list, help_text='Goals the organization pursues in this event')),
                ('influence_mechanisms', models.JSONField(default=list, help_text='How the organization exerts influence')),
                ('institutional_impact', models.TextField(blank=True, help_text='Impact on the institution/organization')),
                ('internal_dynamics', models.TextField(blank=True, help_text='Internal organizational dynamics revealed')),
                ('event', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_involvements', to='narrative.eventpage')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_involvements', to='narrative.organizationpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'unique_together': {('event', 'organization')},
            },
        ),
    ]
