# Generated by Django 5.2.9 on 2026-01-02 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narrative', '0004_objectindexpage_objectpage_locationinvolvement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterpage',
            name='episode_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of distinct episodes appeared in (computed)'),
        ),
        migrations.AddField(
            model_name='characterpage',
            name='importance_tier',
            field=models.CharField(choices=[('anchor', 'Anchor (Main Cast)'), ('planet', 'Planet (Recurring)'), ('asteroid', 'Asteroid (One-off)')], default='asteroid', help_text='Narrative importance tier (computed from episode/relationship counts)', max_length=20),
        ),
        migrations.AddField(
            model_name='characterpage',
            name='relationship_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of unique characters co-participated with (computed)'),
        ),
    ]
