# Generated by Django 5.2.9 on 2026-01-05 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narrative', '0005_add_importance_tier_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterpage',
            name='graph_community',
            field=models.PositiveIntegerField(default=0, help_text='Community cluster ID from Louvain detection'),
        ),
        migrations.AddField(
            model_name='characterpage',
            name='graph_x',
            field=models.FloatField(default=0.0, help_text='Pre-computed X position for graph visualization'),
        ),
        migrations.AddField(
            model_name='characterpage',
            name='graph_y',
            field=models.FloatField(default=0.0, help_text='Pre-computed Y position for graph visualization'),
        ),
        migrations.AddField(
            model_name='characterpage',
            name='graph_z',
            field=models.FloatField(default=0.0, help_text='Pre-computed Z position for graph visualization'),
        ),
    ]
