# Generated by Django 5.2.9 on 2026-01-07 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narrative', '0006_add_graph_position_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterpage',
            name='global_id',
            field=models.CharField(blank=True, db_index=True, help_text='GER global entity ID for cross-season identity (e.g., ger_agent_...)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='conflictarc',
            name='global_id',
            field=models.CharField(blank=True, db_index=True, help_text='GER global entity ID for cross-season identity (e.g., ger_arc_...)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='global_id',
            field=models.CharField(blank=True, db_index=True, help_text='GER global entity ID for cross-season identity (e.g., ger_location_...)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='objectpage',
            name='global_id',
            field=models.CharField(blank=True, db_index=True, help_text='GER global entity ID for cross-season identity (e.g., ger_object_...)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='organizationpage',
            name='global_id',
            field=models.CharField(blank=True, db_index=True, help_text='GER global entity ID for cross-season identity (e.g., ger_org_...)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='global_id',
            field=models.CharField(blank=True, db_index=True, help_text='GER global entity ID for cross-season identity (e.g., ger_theme_...)', max_length=100, null=True),
        ),
    ]
