# Generated by Django 5.2.9 on 2026-01-09 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narrative', '0007_add_global_id_for_ger'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpage',
            name='global_id',
            field=models.CharField(blank=True, db_index=True, help_text='GER global entity ID for cross-season identity (e.g., ger_event_...)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='narrativeconnection',
            name='global_id',
            field=models.CharField(blank=True, db_index=True, help_text='GER global entity ID for cross-season identity (e.g., ger_conn_...)', max_length=100, null=True),
        ),
    ]
