# Generated by Django 5.2.9 on 2026-01-29 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narrative', '0009_add_megagraph_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='conflictarc',
            name='series',
            field=models.ForeignKey(blank=True, help_text='Series this arc belongs to (for multi-graph scoping)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conflict_arcs', to='narrative.seriesindexpage'),
        ),
        migrations.AddField(
            model_name='location',
            name='series',
            field=models.ForeignKey(blank=True, help_text='Series this location belongs to (for multi-graph scoping)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='narrative.seriesindexpage'),
        ),
        migrations.AddField(
            model_name='theme',
            name='series',
            field=models.ForeignKey(blank=True, help_text='Series this theme belongs to (for multi-graph scoping)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='narrative.seriesindexpage'),
        ),
    ]
