# Generated by Django 5.2.9 on 2026-02-06 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narrative', '0010_conflictarc_series_location_series_theme_series'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlotBeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabula_uuid', models.CharField(help_text='UUID from Fabula graph (beat_uuid)', max_length=100, unique=True)),
                ('scene_sequence', models.PositiveIntegerField(help_text='Scene number within episode (matches EventPage.scene_sequence)')),
                ('sequence_in_scene', models.PositiveIntegerField(help_text='Beat order within the scene')),
                ('action_description', models.TextField(blank=True, help_text='What happens in this beat')),
                ('emotional_shift', models.TextField(blank=True, help_text='Emotional shift occurring in this beat')),
                ('involved_character_mentions', models.JSONField(blank=True, default=list, help_text='Character names mentioned in this beat')),
                ('key_objects_mentioned', models.JSONField(blank=True, default=list, help_text='Objects mentioned in this beat')),
                ('setting_details', models.TextField(blank=True, help_text='Setting/location details for this beat')),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plot_beats', to='narrative.episodepage')),
            ],
            options={
                'ordering': ['episode', 'scene_sequence', 'sequence_in_scene'],
            },
        ),
        migrations.CreateModel(
            name='EventBeatLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beat_links', to='narrative.eventpage')),
                ('plot_beat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_links', to='narrative.plotbeat')),
            ],
        ),
        migrations.CreateModel(
            name='Act',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabula_uuid', models.CharField(help_text='UUID from Fabula graph (act_uuid)', max_length=100, unique=True)),
                ('number', models.PositiveIntegerField(help_text='Act number within the episode (1-indexed)')),
                ('summary', models.TextField(blank=True, help_text='Brief summary of this act')),
                ('key_moments', models.JSONField(blank=True, default=list, help_text='Notable moments in this act')),
                ('scene_numbers', models.JSONField(blank=True, default=list, help_text='List of scene_sequence ints belonging to this act')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acts', to='narrative.episodepage')),
            ],
            options={
                'ordering': ['episode', 'number'],
                'unique_together': {('episode', 'number')},
            },
        ),
        migrations.AddIndex(
            model_name='plotbeat',
            index=models.Index(fields=['episode', 'scene_sequence'], name='narrative_p_episode_8699a2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='eventbeatlink',
            unique_together={('event', 'plot_beat')},
        ),
    ]
