# Generated by Django 5.2.9 on 2026-02-08 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narrative', '0011_add_act_plotbeat_eventbeatlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='episodepage',
            name='written_by',
            field=models.TextField(blank=True, help_text='Writer credit(s)'),
        ),
    ]
