# Generated by Django 5.2.9 on 2026-02-09 15:52

import django.db.models.deletion
import modelcluster.fields
import modelsearch.index
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narrative', '0012_episodepage_written_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabula_uuid', models.CharField(help_text='UUID from Fabula graph (writer_uuid)', max_length=100, unique=True)),
                ('canonical_name', models.CharField(max_length=255)),
                ('aliases', models.JSONField(blank=True, default=list, help_text='Alternative names or spellings')),
                ('is_pseudonym', models.BooleanField(default=False)),
                ('pseudonym_of_name', models.CharField(blank=True, help_text='Real name if this is a pseudonym', max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Writers',
            },
            bases=(modelsearch.index.Indexed, models.Model),
        ),
        migrations.AddField(
            model_name='episodepage',
            name='has_complete_credits',
            field=models.BooleanField(default=False, help_text='Whether structured writing credits are available'),
        ),
        migrations.AddField(
            model_name='episodepage',
            name='raw_credits_block',
            field=models.TextField(blank=True, help_text='Full credit text extracted from script header'),
        ),
        migrations.AlterField(
            model_name='episodepage',
            name='written_by',
            field=models.TextField(blank=True, help_text='Writer credit(s) - legacy text field'),
        ),
        migrations.CreateModel(
            name='WritingCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('credit_type', models.CharField(blank=True, help_text="WGA credit type: 'Written by', 'Teleplay by', 'Story by'", max_length=100)),
                ('credit_position', models.PositiveIntegerField(default=1, help_text='Order of credit line (1st credit, 2nd credit, etc.)')),
                ('writer_group', models.PositiveIntegerField(default=1, help_text='Position within a credit line')),
                ('group_type', models.CharField(default='Individual', help_text="'Individual' or 'Team'", max_length=50)),
                ('full_credit_line', models.TextField(blank=True, help_text='Raw credit line text')),
                ('source', models.CharField(blank=True, help_text="Credit source: 'File', 'Official', 'BAML'", max_length=50)),
                ('is_wga_standard', models.BooleanField(default=True, help_text='Whether this follows WGA standard credit format')),
                ('episode', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='writing_credits', to='narrative.episodepage')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episode_credits', to='narrative.writer')),
            ],
            options={
                'ordering': ['credit_position', 'writer_group'],
            },
        ),
    ]
