# Generated by Django 5.2.9 on 2026-02-12 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narrative', '0013_add_writer_writingcredit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episodepage',
            name='dominant_tone',
            field=models.CharField(blank=True, help_text='The prevailing emotional/atmospheric tone', max_length=255),
        ),
    ]
