# Generated by Django 5.2.9 on 2026-02-12 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narrative', '0014_increase_dominant_tone_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngagementSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_slug', models.SlugField(max_length=200)),
                ('action', models.CharField(choices=[('request_season', 'Request next season')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Optional context (e.g. next_season_number, referrer)')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['series_slug', 'action'], name='narrative_e_series__61f936_idx'), models.Index(fields=['created_at'], name='narrative_e_created_974bbb_idx')],
            },
        ),
    ]
