# Generated by Django 5.2.9 on 2026-02-15 18:41

from django.db import migrations, models


def backfill_season_numbers(apps, schema_editor):
    """Populate season_number from parent SeasonPage via the page tree."""
    EpisodePage = apps.get_model('narrative', 'EpisodePage')
    SeasonPage = apps.get_model('narrative', 'SeasonPage')
    Page = apps.get_model('wagtailcore', 'Page')

    # Build a map of page path -> season_number
    season_map = {}
    for season in SeasonPage.objects.all():
        page = Page.objects.get(pk=season.pk)
        season_map[page.path] = season.season_number

    # Update each episode with its parent season's number
    step_len = Page.steplen if hasattr(Page, 'steplen') else 4
    for episode in EpisodePage.objects.all():
        page = Page.objects.get(pk=episode.pk)
        parent_path = page.path[:-step_len]
        sn = season_map.get(parent_path)
        if sn and episode.season_number != sn:
            episode.season_number = sn
            episode.save(update_fields=['season_number'])


class Migration(migrations.Migration):

    dependencies = [
        ('narrative', '0015_add_engagement_signal'),
    ]

    operations = [
        migrations.AddField(
            model_name='episodepage',
            name='season_number',
            field=models.PositiveIntegerField(default=1, help_text='Denormalized from parent SeasonPage for query-free access'),
        ),
        migrations.RunPython(backfill_season_numbers, migrations.RunPython.noop),
    ]
