# Generated by Django 5.2.9 on 2026-03-26 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narrative', '0017_update_site_hostname'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentMiss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(db_index=True, max_length=2000)),
                ('user_agent', models.TextField(blank=True)),
                ('referer', models.URLField(blank=True, max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Agent 404 miss',
                'verbose_name_plural': 'Agent 404 misses',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='narrative_a_created_95dd50_idx'), models.Index(fields=['path', 'created_at'], name='narrative_a_path_9e4929_idx')],
            },
        ),
    ]
