# Generated by Django 5.2.9 on 2026-04-09 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narrative', '0018_agent_miss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventparticipation',
            name='importance',
            field=models.CharField(blank=True, help_text='primary, secondary, background, etc.', max_length=255),
        ),
    ]
