# Generated by Django 5.2.9 on 2026-07-16 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('narrative', '0019_widen_importance_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='characterepisodeprofile',
            options={'ordering': ['episode__season_number', 'episode__episode_number'], 'verbose_name': 'Character Episode Profile', 'verbose_name_plural': 'Character Episode Profiles'},
        ),
        migrations.AlterModelOptions(
            name='episodepage',
            options={'ordering': ['season_number', 'episode_number']},
        ),
        migrations.AlterModelOptions(
            name='eventpage',
            options={'ordering': ['episode__season_number', 'episode__episode_number', 'scene_sequence', 'sequence_in_scene']},
        ),
    ]
