# Generated by Django 5.2.9 on 2026-07-16 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narrative', '0020_alter_characterepisodeprofile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='narrativeconnection',
            name='cross_episode_reasoning',
            field=models.TextField(blank=True, help_text='Why this connection matters across episodes (event layer, cross-episode scope only)'),
        ),
        migrations.AddField(
            model_name='narrativeconnection',
            name='from_episode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_episode_connections', to='narrative.episodepage'),
        ),
        migrations.AddField(
            model_name='narrativeconnection',
            name='inferred_by',
            field=models.CharField(blank=True, help_text='Provenance passthrough (e.g. llm_cross_episode_arc)', max_length=100),
        ),
        migrations.AddField(
            model_name='narrativeconnection',
            name='layer',
            field=models.CharField(choices=[('event', 'Event layer'), ('beat', 'Beat layer')], default='beat', help_text='Analysis layer: native event edge or beat projection', max_length=10),
        ),
        migrations.AddField(
            model_name='narrativeconnection',
            name='scope',
            field=models.CharField(choices=[('intra_episode', 'Within an episode'), ('cross_episode', 'Across episodes')], default='intra_episode', help_text='Whether the endpoints share an episode', max_length=20),
        ),
        migrations.AddField(
            model_name='narrativeconnection',
            name='to_episode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_episode_connections', to='narrative.episodepage'),
        ),
        migrations.AlterField(
            model_name='narrativeconnection',
            name='connection_type',
            field=models.CharField(choices=[('CAUSAL', 'Causal'), ('FORESHADOWING', 'Foreshadowing'), ('THEMATIC_PARALLEL', 'Thematic Parallel'), ('CHARACTER_CONTINUITY', 'Character Continuity'), ('ESCALATION', 'Escalation'), ('CALLBACK', 'Callback'), ('EMOTIONAL_ECHO', 'Emotional Echo'), ('SYMBOLIC_PARALLEL', 'Symbolic Parallel'), ('TEMPORAL', 'Temporal'), ('NARRATIVELY_FOLLOWS', 'Narratively Follows')], max_length=50),
        ),
        migrations.AlterField(
            model_name='narrativeconnection',
            name='fabula_uuid',
            field=models.CharField(blank=True, db_index=True, help_text='UUID from Fabula graph (connection_uuid) — the event-layer import key', max_length=100),
        ),
        migrations.AddIndex(
            model_name='narrativeconnection',
            index=models.Index(fields=['scope', 'connection_type'], name='narrative_n_scope_8de5b3_idx'),
        ),
    ]
