# Generated by Django 5.2.9 on 2026-07-16 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narrative', '0021_narrativeconnection_cross_episode_reasoning_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conflictarc',
            name='involved_characters',
            field=models.ManyToManyField(blank=True, help_text='Characters involved in this arc (INVOLVED_IN_ARC evidence)', related_name='involved_arcs', to='narrative.characterpage'),
        ),
        migrations.AddField(
            model_name='theme',
            name='related_characters',
            field=models.ManyToManyField(blank=True, help_text='Characters related to this theme (RELATED_TO_THEME evidence)', related_name='related_themes', to='narrative.characterpage'),
        ),
        migrations.CreateModel(
            name='ArcEventMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, choices=[('START', 'Start'), ('CLIMAX', 'Climax'), ('RESOLUTION', 'Resolution')], help_text='Structural role: START | CLIMAX | RESOLUTION (nullable)', max_length=20, null=True)),
                ('episode_ordinal', models.PositiveIntegerField(blank=True, db_index=True, help_text="season*100+episode of the event's episode — makes timeline ordering index-friendly", null=True)),
                ('arc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_memberships', to='narrative.conflictarc')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arc_memberships', to='narrative.eventpage')),
            ],
            options={
                'ordering': ['episode_ordinal'],
                'unique_together': {('event', 'arc')},
            },
        ),
        migrations.CreateModel(
            name='ThemeEventMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode_ordinal', models.PositiveIntegerField(blank=True, db_index=True, help_text="season*100+episode of the event's episode", null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theme_memberships', to='narrative.eventpage')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_memberships', to='narrative.theme')),
            ],
            options={
                'ordering': ['episode_ordinal'],
                'unique_together': {('event', 'theme')},
            },
        ),
    ]
