# Generated by Django 5.2.9 on 2026-07-16 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narrative', '0023_backfill_memberships'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterpage',
            name='arc_summary',
            field=models.TextField(blank=True, help_text='LLM cross-season arc summary (megagraph entity extra, contract v2.4.0)'),
        ),
        migrations.CreateModel(
            name='CharacterSeasonProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_number', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True, help_text="Verbatim per-season portrait from the season's own analysis")),
                ('tier', models.CharField(blank=True, help_text='Importance tier within that season', max_length=20)),
                ('source_database', models.CharField(blank=True, help_text='Season database this portrait came from (e.g. wolfhall_s01)', max_length=100)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_profiles', to='narrative.characterpage')),
            ],
            options={
                'verbose_name': 'Character Season Profile',
                'verbose_name_plural': 'Character Season Profiles',
                'ordering': ['season_number'],
                'unique_together': {('character', 'season_number')},
            },
        ),
    ]
