# Generated by Django 5.2.9 on 2026-08-01 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narrative', '0026_backfill_connection_episodes'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterAffiliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(blank=True, db_index=True, help_text="How the character relates to the organization: leader, member, employee, representative, ally… Free text, not choices — the graph carries a long tail of one-off roles ('omen-bearing', 'gatekeeper') and rejecting them would fail the import.", max_length=64)),
                ('confidence', models.FloatField(blank=True, help_text='Extraction confidence 0-1 from the upstream inference pass', null=True)),
                ('reasoning', models.TextField(blank=True, help_text='Why the graph asserts this affiliation — the narrative claim, in the same spirit as NarrativeConnection.description')),
                ('rank', models.PositiveIntegerField(db_index=True, default=0, help_text="Display order, strongest tie first (0 = primary). Set by the exporter's ranking: role tier, then how much of the series the organization spans, then confidence.")),
                ('is_primary', models.BooleanField(default=False, help_text='Mirrors CharacterPage.affiliated_organization')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliations', to='narrative.characterpage')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_affiliations', to='narrative.organizationpage')),
            ],
            options={
                'ordering': ['rank', 'organization__canonical_name'],
                'unique_together': {('character', 'organization')},
            },
        ),
    ]
