const {chromium} = require('playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const baseURL = process.env.STORY_TEST_BASE_URL || 'http://127.0.0.1:8766';
let browser;

(async () => {
  browser = await chromium.launch({headless: true, executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});
  const context = await browser.newContext({viewport: {width: 1440, height: 1100}, acceptDownloads: true});
  const page = await context.newPage();
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  const output = path.resolve('docs/prototypes');
  fs.mkdirSync(output, {recursive: true});
  const loaded = () => page.waitForFunction(() => !document.querySelector('#story-command').disabled);
  async function send(command) {
    await loaded();
    await page.locator('#story-command').fill(command);
    const response = page.waitForResponse(r => r.url().endsWith('/play/api/turn/') && r.request().method() === 'POST');
    await page.locator('#story-command').press('Enter');
    const result = await response;
    assert.equal(result.status(), 200, await result.text());
    await loaded();
    return result.json();
  }
  await page.goto(baseURL + '/play/dracula/');
  await loaded();
  assert.notEqual(await page.evaluate(() => document.activeElement.id), 'story-command', 'must not steal page focus');
  assert.equal(await page.locator('[data-transcript]').evaluate(el => el.scrollTop), 0, 'new game begins at the start of the transcript');
  await page.screenshot({path: output + '/dracula-terminal-desktop.png', fullPage: true});
  let state = await send('examine window');
  assert.equal(state.authored, 1);
  const authoredText = state.transcript.find(b => b.kind === 'written');
  assert.ok(authoredText);
  const previous = state.transcript;
  await page.reload();
  await loaded();
  const resumed = await (await context.request.get(baseURL + '/play/api/state/')).json();
  assert.deepEqual(resumed.transcript, previous);
  state = await send('examine window');
  assert.equal(state.replays, 1);
  await send('study window');
  await send('tell agatha about mina');
  for (const phrase of ['think about the castle bedroom', 'recall the castle bedroom']) {
    const recalled = await send(phrase);
    assert.equal(recalled.scene.name, 'CASTLE BEDROOM');
    assert.equal(recalled.model_calls, 0);
    await send('return');
  }
  await send('remember the castle');
  await send('examine fireplace');
  await send('examine mirror');
  await send('return to agatha');
  state = await send('ask agatha about blood');
  assert.equal(state.discoveries.length, 3);
  await page.screenshot({path: output + '/dracula-terminal-discovery.png', fullPage: true});
  state = await send('read manuscript');
  assert.equal(state.props.manuscript_held, true);
  assert.equal(state.props.manuscript_read, true);
  const manuscriptPassage = state.transcript.at(-2).text;
  await send('return manuscript');
  await send('close bag');
  state = await send('read manuscript');
  assert.equal(state.props.manuscript_held, false);
  assert.match(state.transcript.at(-1).text, /closed bag/);
  await send('open bag');
  state = await send('read manuscript');
  assert.equal(state.transcript.at(-2).text, manuscriptPassage);
  state = await send('ask agatha about manuscript');
  await page.screenshot({path: output + '/dracula-terminal-manuscript.png', fullPage: true});
  await send('return manuscript');
  await send('freeze world');
  const before = state.authored;
  state = await send('examine bag');
  assert.equal(state.authored, before);
  assert.equal(state.frozen, true);
  await page.locator('.story-workshop summary').click();
  const downloadPromise = page.waitForEvent('download');
  await page.locator('[data-download]').click();
  const download = await downloadPromise;
  const offlinePath = output + '/fabula-dracula-written-world.html';
  await download.saveAs(offlinePath);
  const offline = await context.newPage();
  let networkCalls = 0;
  await offline.route(/^https?:/, route => {networkCalls++; route.abort();});
  await offline.goto('file://' + offlinePath);
  await offline.waitForFunction(() => !document.querySelector('#story-command').disabled);
  assert.equal(await offline.locator('[data-discoveries]').innerText(), '3');
  offline.once('dialog', dialog => dialog.accept());
  await offline.locator('[data-restart]').click();
  assert.equal(await offline.locator('[data-discoveries]').innerText(), '0');
  for (const phrase of ['think about the castle bedroom', 'recall the castle bedroom']) {
    await offline.locator('#story-command').fill(phrase);
    await offline.locator('#story-command').press('Enter');
    assert.equal(await offline.locator('[data-location]').innerText(), 'CASTLE BEDROOM');
    await offline.locator('#story-command').fill('return');
    await offline.locator('#story-command').press('Enter');
  }
  for (const command of ['read manuscript', 'close bag', 'inventory', 'open bag', 'return manuscript', 'read manuscript', 'tell agatha about mina', 'remember the castle', 'examine mirror', 'return', 'ask agatha about blood', 'examine window']) {
    await offline.locator('#story-command').fill(command);
    await offline.locator('#story-command').press('Enter');
  }
  assert.equal(await offline.locator('[data-discoveries]').innerText(), '3');
  assert.ok(Number(await offline.locator('[data-replays]').textContent()) >= 1);
  assert.ok((await offline.locator('[data-transcript]').innerText()).includes(manuscriptPassage));
  assert.equal(networkCalls, 0);
  await offline.reload();
  await offline.waitForFunction(() => !document.querySelector('#story-command').disabled);
  assert.equal(await offline.locator('[data-discoveries]').innerText(), '3');
  const mobile = await browser.newContext({viewport: {width: 390, height: 844}, isMobile: true, hasTouch: true, deviceScaleFactor: 1});
  const phone = await mobile.newPage();
  await phone.goto(baseURL + '/play/dracula/');
  await phone.waitForFunction(() => !document.querySelector('#story-command').disabled);
  assert.equal(await phone.evaluate(() => document.documentElement.scrollWidth > innerWidth), false, 'mobile horizontal overflow');
  assert.equal(await phone.locator('[data-transcript]').evaluate(el => el.scrollTop), 0, 'mobile opening is not clipped by automatic scroll');
  await phone.screenshot({path: output + '/dracula-terminal-mobile.png', fullPage: true});
  const embed = await context.newPage();
  await embed.goto(baseURL + '/play/dracula/embed/');
  await embed.waitForFunction(() => !document.querySelector('#story-command').disabled);
  assert.equal(await embed.locator('[data-discoveries]').innerText(), '3');
  assert.deepEqual(errors, []);
  console.log(JSON.stringify({desktop: 'passed', mobile: 'passed', resume: 'passed', authoredReplay: 'passed', freeze: 'passed', embed: 'passed', offlineFullInvestigation: 'passed', physicalInteractions: 'passed', offlineManuscript: 'passed', offlineNetworkCalls: networkCalls, browserErrors: errors, artifacts: output}, null, 2));
  await browser.close();
})().catch(error => {console.error(error); process.exitCode = 1;}).finally(async () => {if (browser) await browser.close();});
