# Generated by Django 5.2.9 on 2026-10-08 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorldPassage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('world', models.CharField(max_length=64)),
                ('key', models.CharField(max_length=200)),
                ('packet_hash', models.CharField(max_length=64)),
                ('backend', models.CharField(max_length=20)),
                ('kind', models.CharField(max_length=20)),
                ('text', models.TextField()),
                ('sources', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('written_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='world_passages', to='adventure.playthrough')),
            ],
            options={
                'indexes': [models.Index(fields=['world', 'key'], name='adventure_world_key')],
                'constraints': [models.UniqueConstraint(fields=('world', 'key', 'packet_hash', 'backend'), name='adventure_world_passage_once')],
            },
        ),
    ]
