# Generated by Django 5.2.9 on 2026-10-08 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0002_world_passage'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='worldpassage',
            name='adventure_world_passage_once',
        ),
        migrations.AddField(
            model_name='worldpassage',
            name='retired_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='worldpassage',
            name='retired_reason',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddConstraint(
            model_name='worldpassage',
            constraint=models.UniqueConstraint(condition=models.Q(('retired_at__isnull', True)), fields=('world', 'key', 'packet_hash', 'backend'), name='adventure_world_passage_live_once'),
        ),
    ]
