# Generated by Django 5.2.9 on 2026-10-08 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0003_retire_passages'),
    ]

    operations = [
        migrations.AddField(
            model_name='worldpassage',
            name='carried_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carried_to', to='adventure.worldpassage'),
        ),
    ]
